module.exports = [
  {
    category: "kids / family / toddler",
    prompt: "Toddler friendly movies that include rabbits",
    expectedTopPicks: ["Peter Rabbit", "Hop", "Peter Rabbit 2"],
    likelyFalsePositives: ["Watership Down", "Zootopia", "Bunny"],
    likelyWeakness: "Backup quality can still drift toward odd rabbit-adjacent titles if the live pool is thin.",
  },
  {
    category: "kids / family / toddler",
    prompt: "A movie for kids that has dogs but isn't too loud or chaotic",
    expectedTopPicks: ["Lady and the Tramp", "Bolt", "101 Dalmatians"],
    likelyFalsePositives: ["The Secret Life of Pets", "Spirited Away", "Air Bud"],
    likelyWeakness: "Entity misses used to win here; this should now stay dog-centered, but low-chaos calibration is still heuristic.",
  },
  {
    category: "animals / entities / creatures",
    prompt: "A movie with foxes for younger kids",
    expectedTopPicks: ["Robin Hood", "Fantastic Mr. Fox", "Zootopia"],
    likelyFalsePositives: ["The Fox and the Hound", "The Fox and the Child", "Isle of Dogs"],
    likelyWeakness: "The system understands foxes, but younger-kids fit vs older-kids wit is still a judgment call.",
  },
  {
    category: "crowd-pleasers",
    prompt: "Something everyone will agree on",
    expectedTopPicks: ["Paddington 2", "Hidden Figures", "The Martian"],
    likelyFalsePositives: ["Under the Skin", "Tenet", "Everything Everywhere All at Once"],
    likelyWeakness: "Consensus prompts are broad and can still over-reward prestige unless low-regret stays strong.",
  },
  {
    category: "crowd-pleasers",
    prompt: "A crowd-pleaser that still feels smart",
    expectedTopPicks: ["Knives Out", "Ocean's Eleven", "The Martian"],
    likelyFalsePositives: ["Tenet", "Primer", "Tinker Tailor Soldier Spy"],
    likelyWeakness: "Smart-vs-accessible balance can still wobble toward overly brainy picks if the candidate pool is niche.",
  },
  {
    category: "smart-but-accessible",
    prompt: "A smart sci-fi movie that won't melt my brain",
    expectedTopPicks: ["The Martian", "Minority Report", "Edge of Tomorrow"],
    likelyFalsePositives: ["Primer", "Coherence", "Annihilation"],
    likelyWeakness: "Accessibility is inferred from stimulation and clarity proxies, not a true comprehension model.",
  },
  {
    category: "cozy / gentle / low-intensity",
    prompt: "A cozy, gentle movie for a quiet night",
    expectedTopPicks: ["Paddington 2", "Julie & Julia", "Kiki's Delivery Service"],
    likelyFalsePositives: ["Little Women", "The Secret Life of Walter Mitty", "Amelie"],
    likelyWeakness: "Cozy prompts still rely heavily on tone heuristics because there is no dedicated coziness enrichment table yet.",
  },
  {
    category: "spooky-but-safe",
    prompt: "Something spooky but safe for a 6 year old",
    expectedTopPicks: ["Monsters, Inc.", "Hotel Transylvania", "The Nightmare Before Christmas"],
    likelyFalsePositives: ["Coraline", "Goosebumps", "ParaNorman"],
    likelyWeakness: "Mild-spooky calibration is good but still imperfect around titles that are family movies yet genuinely creepy.",
  },
  {
    category: "sweeping historical epics",
    prompt: "Sweeping epics like Dances with Wolves or Last of the Mohicans",
    expectedTopPicks: ["Legends of the Fall", "The New World", "Atonement"],
    likelyFalsePositives: ["Braveheart", "Gladiator", "Mad Max: Fury Road"],
    likelyWeakness: "This lane can drift into generic action spectacle if immersive-romantic weighting softens too much.",
  },
  {
    category: "narrow entity asks that require semantic understanding",
    prompt: "A gentle movie with rabbits that older kids and adults will both like",
    expectedTopPicks: ["Peter Rabbit", "Peter Rabbit 2", "Wallace & Gromit: The Curse of the Were-Rabbit"],
    likelyFalsePositives: ["Watership Down", "Zootopia", "Donnie Darko"],
    likelyWeakness: "Cross-audience prompts with a narrow entity ask still need better franchise-level enrichment.",
  },
  {
    category: "narrow entity asks that require semantic understanding",
    prompt: "A movie with wolves that's safe for a toddler",
    expectedTopPicks: ["Alpha and Omega", "The Jungle Bunch 2: World Tour", "Wolfwalkers"],
    likelyFalsePositives: ["The Grey", "Balto", "The Wolf of Wall Street"],
    likelyWeakness: "This is still a weak lane because wolves are semantically modeled less richly than rabbits, dogs, or foxes.",
  },
];
