module.exports = [
  {
    prompt: "Toddler friendly movies that include rabbits",
    acceptedTopTitles: ["Peter Rabbit", "Hop", "Peter Rabbit 2"],
    expectedTopThree: ["Peter Rabbit", "Hop", "Peter Rabbit 2"],
    candidates: [
      {
        title: "Peter Rabbit",
        overview: "Peter Rabbit and his sisters get into playful trouble in a bright family adventure built around the rabbit hero.",
        genre_ids: [12, 35, 10751],
        runtime: 95,
        popularity: 62,
        vote_average: 6.6,
        vote_count: 4200,
        us_certification: "PG",
        keyword_names: ["rabbit", "bunny", "family", "animal adventure"],
      },
      {
        title: "Hop",
        overview: "The Easter Bunny's teenage son heads to Hollywood in a silly live-action family comedy full of rabbits and bright energy.",
        genre_ids: [35, 10751, 14],
        runtime: 95,
        popularity: 48,
        vote_average: 5.8,
        vote_count: 1800,
        us_certification: "PG",
        keyword_names: ["easter bunny", "rabbit", "family comedy"],
      },
      {
        title: "Peter Rabbit 2",
        overview: "Peter Rabbit returns for another family-friendly adventure with gentle peril and a lot of rabbit-centered chaos.",
        genre_ids: [12, 35, 10751],
        runtime: 93,
        popularity: 39,
        vote_average: 7.1,
        vote_count: 900,
        us_certification: "PG",
        keyword_names: ["rabbit", "family", "animal adventure"],
      },
      {
        title: "Zootopia",
        overview: "A smart animated city mystery led by a rabbit officer, but it plays broader and busier than a toddler-first pick.",
        genre_ids: [16, 12, 35, 10751],
        runtime: 108,
        popularity: 95,
        vote_average: 7.7,
        vote_count: 16000,
        us_certification: "PG",
        keyword_names: ["rabbit", "city", "animal"],
      },
      {
        title: "Watership Down",
        overview: "A bleak animated story about rabbits surviving danger and violence in the wild.",
        genre_ids: [16, 18, 12],
        runtime: 92,
        popularity: 18,
        vote_average: 7.2,
        vote_count: 1100,
        us_certification: "PG",
        keyword_names: ["rabbit", "survival", "danger"],
      },
    ],
  },
  {
    prompt: "A crowd-pleaser that still feels smart",
    acceptedTopTitles: ["Knives Out", "Ocean's Eleven", "The Martian"],
    candidates: [
      {
        title: "Knives Out",
        overview: "A funny, stylish murder mystery with broad appeal and enough cleverness to feel sharper than a generic crowd-pleaser.",
        genre_ids: [35, 9648, 80],
        runtime: 131,
        popularity: 76,
        vote_average: 7.8,
        vote_count: 12000,
        us_certification: "PG-13",
      },
      {
        title: "Ocean's Eleven",
        overview: "A slick heist movie with movie-star ease, high likability, and smart playful momentum.",
        genre_ids: [80, 53, 35],
        runtime: 116,
        popularity: 58,
        vote_average: 7.7,
        vote_count: 11000,
        us_certification: "PG-13",
      },
      {
        title: "The Martian",
        overview: "An accessible sci-fi survival crowd-pleaser that stays witty and thoughtful without getting too dense.",
        genre_ids: [18, 12, 878],
        runtime: 144,
        popularity: 72,
        vote_average: 7.7,
        vote_count: 20000,
        us_certification: "PG-13",
      },
      {
        title: "Tenet",
        overview: "A flashy concept movie that asks a lot more decoding than a low-regret crowd pick usually should.",
        genre_ids: [28, 53, 878],
        runtime: 150,
        popularity: 60,
        vote_average: 7.1,
        vote_count: 9000,
        us_certification: "PG-13",
      },
    ],
  },
  {
    prompt: "Something everyone will agree on",
    acceptedTopTitles: ["Paddington 2", "The Martian", "Hidden Figures"],
    candidates: [
      {
        title: "Paddington 2",
        overview: "A warm, funny family adventure with low-regret charm and unusually strong audience buy-in.",
        genre_ids: [35, 12, 10751],
        runtime: 104,
        popularity: 42,
        vote_average: 7.8,
        vote_count: 2200,
        us_certification: "PG",
      },
      {
        title: "Hidden Figures",
        overview: "An uplifting crowd-pleasing drama with accessible momentum and broad shared-watch appeal.",
        genre_ids: [18, 36],
        runtime: 127,
        popularity: 38,
        vote_average: 7.8,
        vote_count: 9500,
        us_certification: "PG",
      },
      {
        title: "The Martian",
        overview: "A witty, accessible survival sci-fi movie that tends to play well with broad groups.",
        genre_ids: [18, 12, 878],
        runtime: 144,
        popularity: 72,
        vote_average: 7.7,
        vote_count: 20000,
        us_certification: "PG-13",
      },
      {
        title: "Under the Skin",
        overview: "A chilly, alienating art film that is more admired than agreed-on.",
        genre_ids: [18, 878, 53],
        runtime: 108,
        popularity: 20,
        vote_average: 6.3,
        vote_count: 3300,
        us_certification: "R",
      },
    ],
  },
  {
    prompt: "Sweeping epics like Dances with Wolves or Last of the Mohicans",
    acceptedTopTitles: ["Legends of the Fall", "The New World", "Atonement"],
    candidates: [
      {
        title: "Legends of the Fall",
        overview: "A sweeping historical romance with wilderness scale, melodramatic feeling, and old-fashioned epic sprawl.",
        genre_ids: [18, 10749, 10752],
        runtime: 133,
        popularity: 28,
        vote_average: 7.4,
        vote_count: 1700,
        us_certification: "R",
      },
      {
        title: "The New World",
        overview: "A deliberate historical romance with immersive landscapes and expansive, contemplative scale.",
        genre_ids: [18, 36, 10749],
        runtime: 151,
        popularity: 19,
        vote_average: 6.7,
        vote_count: 1400,
        us_certification: "PG-13",
      },
      {
        title: "Atonement",
        overview: "A sweeping wartime romance with period elegance and emotional scale.",
        genre_ids: [18, 10749, 10752],
        runtime: 123,
        popularity: 31,
        vote_average: 7.6,
        vote_count: 6300,
        us_certification: "R",
      },
      {
        title: "Mad Max: Fury Road",
        overview: "A spectacular action movie, but it is more assaultive propulsion than romantic historical epic.",
        genre_ids: [28, 12, 878],
        runtime: 121,
        popularity: 86,
        vote_average: 7.6,
        vote_count: 23000,
        us_certification: "R",
      },
    ],
  },
  {
    prompt: "A movie for kids that has dogs but isn't too loud or chaotic",
    acceptedTopTitles: ["Lady and the Tramp", "Bolt", "101 Dalmatians"],
    candidates: [
      {
        title: "Lady and the Tramp",
        overview: "A gentle dog-centered family romance with warm energy and low-chaos storytelling.",
        genre_ids: [16, 10749, 10751],
        runtime: 76,
        popularity: 30,
        vote_average: 7.1,
        vote_count: 5400,
        us_certification: "G",
        keyword_names: ["dog", "dogs", "puppy", "family"],
      },
      {
        title: "Bolt",
        overview: "A funny, bright animated dog adventure that stays family-friendly and easy for kids to follow.",
        genre_ids: [16, 35, 10751],
        runtime: 96,
        popularity: 33,
        vote_average: 6.8,
        vote_count: 6300,
        us_certification: "PG",
        keyword_names: ["dog", "animal", "family"],
      },
      {
        title: "101 Dalmatians",
        overview: "A classic dog-heavy family caper with some chase energy but still a clear kids lane.",
        genre_ids: [12, 35, 10751],
        runtime: 103,
        popularity: 29,
        vote_average: 5.8,
        vote_count: 2400,
        us_certification: "G",
        keyword_names: ["dog", "puppy", "family"],
      },
      {
        title: "The Secret Life of Pets",
        overview: "A dog-centric animated comedy with louder, busier comic energy than the prompt really wants.",
        genre_ids: [16, 35, 10751],
        runtime: 87,
        popularity: 56,
        vote_average: 6.4,
        vote_count: 8000,
        us_certification: "PG",
        keyword_names: ["dog", "dogs", "pets"],
      },
      {
        title: "Spirited Away",
        overview: "A brilliant fantasy for older kids, but it is not dog-centered and it asks for more intensity and focus than this prompt wants.",
        genre_ids: [16, 14, 10751],
        runtime: 125,
        popularity: 79,
        vote_average: 8.5,
        vote_count: 17000,
        us_certification: "PG",
        keyword_names: ["spirit world", "fantasy", "coming of age"],
      },
    ],
  },
  {
    prompt: "Something spooky but safe for a 6 year old",
    acceptedTopTitles: ["Monsters, Inc.", "Hotel Transylvania", "The Nightmare Before Christmas"],
    candidates: [
      {
        title: "Monsters, Inc.",
        overview: "A playful monster movie with mild spooky flavor, warmth, and a very safe family landing.",
        genre_ids: [16, 35, 10751],
        runtime: 92,
        popularity: 64,
        vote_average: 7.8,
        vote_count: 18000,
        us_certification: "G",
      },
      {
        title: "Hotel Transylvania",
        overview: "A bright spooky-family comedy that keeps the monster fun broad and safe for kids.",
        genre_ids: [16, 35, 10751, 14],
        runtime: 91,
        popularity: 54,
        vote_average: 6.9,
        vote_count: 8500,
        us_certification: "PG",
      },
      {
        title: "The Nightmare Before Christmas",
        overview: "A musical fantasy with spooky imagery, but still playful and family-safe in practice.",
        genre_ids: [14, 16, 10751],
        runtime: 76,
        popularity: 51,
        vote_average: 7.8,
        vote_count: 9300,
        us_certification: "PG",
      },
      {
        title: "Coraline",
        overview: "A brilliant movie, but its creepy peril and intensity push it closer to a stretch pick for a cautious 6 year old.",
        genre_ids: [16, 14, 10751],
        runtime: 100,
        popularity: 47,
        vote_average: 7.8,
        vote_count: 8500,
        us_certification: "PG",
      },
    ],
  },
  {
    prompt: "A smart sci-fi movie that won't melt my brain",
    acceptedTopTitles: ["The Martian", "Minority Report", "Edge of Tomorrow"],
    candidates: [
      {
        title: "The Martian",
        overview: "A witty, smart sci-fi survival movie that stays clear, accessible, and broadly enjoyable.",
        genre_ids: [18, 12, 878],
        runtime: 144,
        popularity: 72,
        vote_average: 7.7,
        vote_count: 20000,
        us_certification: "PG-13",
      },
      {
        title: "Minority Report",
        overview: "A sharp, idea-driven sci-fi thriller that stays legible even while it gets twisty.",
        genre_ids: [28, 53, 878],
        runtime: 145,
        popularity: 44,
        vote_average: 7.4,
        vote_count: 8200,
        us_certification: "PG-13",
      },
      {
        title: "Edge of Tomorrow",
        overview: "A clever, propulsive sci-fi action movie with enough concept to feel smart without getting opaque.",
        genre_ids: [28, 878],
        runtime: 113,
        popularity: 68,
        vote_average: 7.6,
        vote_count: 14000,
        us_certification: "PG-13",
      },
      {
        title: "Primer",
        overview: "A brainy time-travel puzzle that is much more demanding than the prompt wants.",
        genre_ids: [878, 18, 53],
        runtime: 77,
        popularity: 14,
        vote_average: 6.8,
        vote_count: 2200,
        us_certification: "PG-13",
      },
    ],
  },
  {
    prompt: "A movie with foxes for younger kids",
    acceptedTopTitles: ["Robin Hood", "Fantastic Mr. Fox", "Doraemon: Nobita and the Kingdom of Clouds"],
    candidates: [
      {
        title: "Robin Hood",
        overview: "Disney's bright animal adventure puts a fox front and center in a gentle, younger-kids-friendly lane.",
        genre_ids: [16, 12, 10751],
        runtime: 83,
        popularity: 36,
        vote_average: 7.3,
        vote_count: 4700,
        us_certification: "G",
        keyword_names: ["fox", "animal", "family"],
      },
      {
        title: "Fantastic Mr. Fox",
        overview: "A funny fox-centered family movie with a drier, slightly older-kids tone.",
        genre_ids: [12, 16, 35, 10751],
        runtime: 87,
        popularity: 34,
        vote_average: 7.8,
        vote_count: 5000,
        us_certification: "PG",
        keyword_names: ["fox", "animal", "family"],
      },
      {
        title: "Zootopia",
        overview: "A smart animal city mystery with a fox lead, but the rabbit is more central and the lane is broader than younger-kids-first.",
        genre_ids: [16, 12, 35, 10751],
        runtime: 108,
        popularity: 95,
        vote_average: 7.7,
        vote_count: 16000,
        us_certification: "PG",
        keyword_names: ["fox", "rabbit", "animal"],
      },
    ],
  },
];
