const assert = require('node:assert/strict');
const {parseReelbotIntent}=require('../ai/intentParser');
const {passesRecommendationContract, recommendationCacheScope, needsVerifiedContentGuide}=require('../ai/recommendationContract');
assert.equal(needsVerifiedContentGuide('for a four year old, no scary scenes'), true);
assert.equal(needsVerifiedContentGuide('absolutely no violence'), true);
assert.equal(needsVerifiedContentGuide('something less violent'), false);
const {classifyAskIntent, ASK_INTENTS}=require('../src/ask/askIntent');
const {updateConversationForPrompt}=require('../src/ask/conversationState');
const base={id:1,genre_ids:[28,35],runtime:97,release_date:'1998-01-01'};
const combined=parseReelbotIntent('A funny 90s action movie under two hours, no horror.');
assert.ok(passesRecommendationContract(base,combined,{final:true}));
for(const movie of [{...base,runtime:121},{...base,genre_ids:[35]},{...base,release_date:'2010-01-01'},{...base,genre_ids:[28,35,27]},{...base,runtime:null}]) assert.equal(passesRecommendationContract(movie,combined,{final:true}),false);
for(const prompt of ['I want a tense 90-minute thriller.','A thriller no longer than 90 minutes.']) assert.equal(parseReelbotIntent(prompt).hard_filters.max_runtime_minutes,90);
assert.equal(parseReelbotIntent('under 2 hours').hard_filters.max_runtime_minutes,119);
assert.deepEqual(parseReelbotIntent('I loved Interstellar.').anchors.title,'Interstellar');
assert.equal(parseReelbotIntent('Nothing too heavy').emotional_tolerance.level,'light');
assert.equal(parseReelbotIntent('gentle for a four year old').audience_age,'preschool');
assert.equal(parseReelbotIntent('A Japanese drama from the 1960s').hard_filters.time_constraint.range.min_year,1960);
assert.equal(passesRecommendationContract({...base,runtime:7},parseReelbotIntent('A feature film under 10 minutes'),{final:true}),false);
assert.notEqual(recommendationCacheScope({bounded_pool:true,candidate_pool_ids:[1,2]},{}),recommendationCacheScope({bounded_pool:true,candidate_pool_ids:[3,4]},{}));
assert.notEqual(recommendationCacheScope({bounded_pool:true,candidate_pool_ids:[]},{}),recommendationCacheScope({},{}));
assert.doesNotThrow(()=>recommendationCacheScope({candidate_pool_ids:'bad'},{}));
const state={anchorMovie:{id:1,title:'One',runtime:110,release_date:'1998-01-01'},recommendationHistory:[{id:1,status:'recommended'}],activeRequest:'something funny'};
for(const prompt of ['shorter','less violent',"I've seen that",'something newer','what about something funnier?']) assert.equal(classifyAskIntent({prompt,context:{page:'movie_detail'},conversation:state}),ASK_INTENTS.REFINE_RECOMMENDATION,prompt);
assert.equal(classifyAskIntent({prompt:'why this one?',context:{page:'movie_detail'},conversation:state}),ASK_INTENTS.CURRENT_MOVIE_QUESTION);
assert.equal(updateConversationForPrompt(state,'shorter',ASK_INTENTS.REFINE_RECOMMENDATION).activeConstraints.maxRuntime,109);
assert.equal(updateConversationForPrompt(state,'something newer',ASK_INTENTS.REFINE_RECOMMENDATION).activeConstraints.minYear,1999);
assert.equal(updateConversationForPrompt(state,"I've seen that",ASK_INTENTS.REFINE_RECOMMENDATION).recommendationHistory[0].status,'rejected');
assert.equal(classifyAskIntent({prompt:'Where should I start?',context:{page:'person'}}),ASK_INTENTS.CURRENT_SET_RECOMMENDATION);
console.log('Recommendation contracts, cache isolation, negation, age, decade and follow-up regressions passed.');

const adultComfort = parseReelbotIntent('Sunday night feel good movie for adults');
assert.equal(adultComfort.audience_age, 'adults');
assert.ok(adultComfort.soft_preferences.preference_signals.includes('comforting'));
assert.ok(adultComfort.query_expansion.title_hints.includes('Julie & Julia'));
const toyStory = {...base,title:'Toy Story 5',genre_ids:[16,10751,35,12]};
for (const final of [false,true]) assert.equal(passesRecommendationContract(toyStory,adultComfort,{final}),false);
assert.equal(passesRecommendationContract({...base,title:'Chef',genre_ids:[35,18]},adultComfort),true);
assert.equal(passesRecommendationContract({...base,title:'Adult animation',genre_ids:[16,35]},adultComfort),true);
for (const prompt of ['A feel good family movie','An animated feel good movie for adults','Something like Toy Story for adults']) assert.equal(passesRecommendationContract(toyStory,parseReelbotIntent(prompt)),true,prompt);
console.log('Adult comfort retrieval and audience constraints preserve family and animation requests.');

const {getRecommendationFitBreakdown} = require('../ai/recommendationScoring');
const animationFit = getRecommendationFitBreakdown(toyStory,parseReelbotIntent('An animated feel good movie for adults'));
assert.ok(!animationFit.penalties.includes('too_child_coded_for_adult_cozy'));
