const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const { createHash } = require('node:crypto');
const { parseReelbotIntent } = require('../ai/intentParser');
const { deriveMovieSignals } = require('../ai/movieSignals');
const { isBroadDiscoveryRequest, getExposurePenaltyMultiplier } = require('../ai/recommendationNovelty');
const { classifyAskIntent, ASK_INTENTS } = require('../src/ask/askIntent');
const source = fs.readFileSync(require.resolve('../index.js'), 'utf8');
const context = vm.createContext({process, console, Set, createHash, deriveMovieSignals, matchesAnyGenre:(ids,wanted)=>ids.some(id=>wanted.includes(id))});
vm.runInContext(source.slice(source.indexOf('const BEHAVIOR_LANE_GENRE_MAP'),source.indexOf('const BEHAVIOR_TONE_REASON_LABELS')) + '\nthis.norm=normalizeBehavioralMemory;this.score=getBehavioralMemoryScore;this.key=getBehavioralMemoryCacheKey;',context);
const movie = {id:550,title:'Example',runtime:110,genre_ids:[18],overview:'A drama.',vote_average:8,vote_count:10000};
const memory = {savedMovieIds:[550],seenMovieIds:[551],hiddenMovieIds:[552],recentMovieIds:[553],userProfile:{hardAvoidMovieIds:[554]}};
const normalized = context.norm(memory);
const renormalized = context.norm(normalized);
for (const field of ['savedMovieIds','seenMovieIds','hiddenMovieIds','recentMovieIds']) assert.deepEqual([...renormalized[field]],[...normalized[field]],field);
assert.deepEqual([...renormalized.userProfile.hardAvoidMovieIds],[554]);
for (const field of ['savedMovieIds','seenMovieIds','hiddenMovieIds','recentMovieIds']) {
 assert.notEqual(context.key({[field]:[1]}),context.key({[field]:[2]}),`${field}: no cross-history cache collision`);
 assert.equal(context.key({[field]:[1,2]}),context.key({[field]:[2,1]}),`${field}: order independent`);
}
assert.notEqual(context.key({userProfile:{likedGenres:[35]}}),context.key({userProfile:{likedGenres:[27]}}));
assert.notEqual(context.key({preferredGenres:{35:0.1}}),context.key({preferredGenres:{35:0.2}}));
const intent=parseReelbotIntent('a drama');
const plain=context.score(movie,{},intent).score;
const saved=context.score(movie,context.norm({savedMovieIds:[550]}),intent);
assert.equal(saved.score-plain,5.5);assert.ok(saved.reasons.includes('saved-positive'));
const recent=context.score(movie,context.norm({recentMovieIds:[550]}),intent);
assert.equal(recent.score-plain,-9);assert.ok(recent.reasons.includes('recently-viewed'));
assert.ok(context.score(movie,context.norm({seenMovieIds:[550]}),intent).reasons.includes('seen-deprioritized'));
assert.equal(context.score(movie,context.norm({hiddenMovieIds:[550]}),intent).score,-1000);
assert.equal(context.score(movie,context.norm({userProfile:{hardAvoidMovieIds:[550]}}),intent).score,-1000);
assert.ok(Math.abs(context.score(movie,{preferredGenres:{18:1000}},intent).score)<=28);
const generic=parseReelbotIntent("I don't know what I want. Just give me something really good that I might not immediately think of.");
generic.query_type='GENRE_OR_VIBE';generic.hard_filters.min_runtime_minutes=40;generic.implicit_feature_runtime_floor=true;
assert.equal(isBroadDiscoveryRequest(generic),true);assert.equal(getExposurePenaltyMultiplier(generic),1.35);
assert.equal(isBroadDiscoveryRequest({...generic,implicit_feature_runtime_floor:false}),false);
assert.equal(isBroadDiscoveryRequest({...generic,hard_filters:{...generic.hard_filters,max_runtime_minutes:100}}),false);
assert.equal(isBroadDiscoveryRequest({...generic,hard_filters:{min_runtime_minutes:121}}),false);
for(const prompt of ['Find me a movie with Keanu Reeves','Recommend a movie about space','A movie with friends','What movie should I watch with friends?']) assert.notEqual(classifyAskIntent({prompt,context:{page:'home'}}),ASK_INTENTS.MOVIE_IDENTIFICATION,prompt);
for(const prompt of ['What was that movie where a guy wakes up every day with no memory?','Which film was that with the hotel and the backwards dream levels?','I remember a movie about a sound engineer','Identify the movie where a man relives a day']) assert.equal(classifyAskIntent({prompt,context:{page:'movie_detail'}}),ASK_INTENTS.MOVIE_IDENTIFICATION,prompt);
console.log('History scoring/idempotence/cache isolation, bounded taste weights, broad-discovery penalty and intent boundary checks passed.');

const quietIntent = parseReelbotIntent('Sunday night feel good movie for adults');
const fastMovie = {...movie,genre_ids:[28,12]};
const fastMemory = {pacePreferences:{fast:4},userProfile:{preferredTraits:{pace:['fast']}}};
assert.equal(context.score(fastMovie,fastMemory,quietIntent).score,context.score(fastMovie,{},quietIntent).score);
assert.ok(context.score(fastMovie,fastMemory,parseReelbotIntent('a fast moving action movie')).score > context.score(fastMovie,{},quietIntent).score);
vm.runInContext(source.slice(source.indexOf('const BEHAVIOR_TONE_REASON_LABELS'),source.indexOf('const scorePickCandidate'))+'\nthis.reason=buildBehavioralPreferenceReason;', context);
context.TMDB_MOVIE_GENRE_LOOKUP = {};
assert.equal(context.reason(fastMovie,fastMemory,quietIntent),'');
assert.match(context.reason(fastMovie,fastMemory,parseReelbotIntent('an action movie')),/faster-moving/);
console.log('Current mood overrides incompatible historical bonuses and taste notes.');
