const assert = require('node:assert/strict');
const {retrieveWithDiscovery,shouldRunSemanticFallback,isDiscoveryBounded,buildDiscoveryPrompt,untestedDiscoveryCandidates} = require('../src/ask/candidateRetrieval');
(async () => {
 let started = [], release;
 const held = new Promise(resolve => {release = resolve;});
 const result = retrieveWithDiscovery({retrieve: async () => {started.push('feed'); await held; return [1];}, discover: async () => {started.push('discovery'); return [2];}, allowDiscovery: true});
 await Promise.resolve();
 assert.deepEqual(started, ['feed', 'discovery'], 'Independent discovery starts before feed retrieval completes');
 release(); assert.deepEqual(await result, {pool: [1], discovered: [2]});
 let calls = 0;
 assert.deepEqual(await retrieveWithDiscovery({retrieve: async () => [3], discover: async () => {calls++;}, allowDiscovery: false}), {pool: [3], discovered: []});
 assert.equal(calls, 0, 'Bounded and ordinary requests gain no discovery call');
 assert.deepEqual(untestedDiscoveryCandidates([{id:1},{id:2}],[{id:1}]),[{id:2}],'A fallback cannot re-rank a previously rejected film');
 assert.equal(shouldRunSemanticFallback({prompt:'An unfamiliar relational story clue'}),true);
 assert.equal(isDiscoveryBounded({candidate_pool_ids:[1,2],is_swap:true}),false,'A cached swap deck may receive a bounded retrieval refill');
 assert.equal(isDiscoveryBounded({candidate_pool_ids:[1,2],is_swap:true,bounded_pool:true}),true,'An explicit collection boundary never expands');
 assert.equal(isDiscoveryBounded({candidate_pool_ids:[1,2]}),true,'Explicit fresh candidate sets remain bounded');
 assert.match(buildDiscoveryPrompt('An active request',{max_runtime_minutes:80},'Previous title'),/80 minutes/);
 assert.equal(shouldRunSemanticFallback({prompt:'An answerable story',discoveryPerformed:true}),true,'A failed semantic shortlist may receive one search for new hypotheses');
 assert.match(buildDiscoveryPrompt('A complete request',{max_runtime_minutes:80},'', ['Previously considered film']),/do not repeat these titles: Previously considered film/);
 for (const block of [{bounded:true},{attempted:true},{prompt:''}]) assert.equal(shouldRunSemanticFallback({prompt:'A request',...block}),false,'Fallback runs at most once and never escapes bounded pools');
 await assert.rejects(retrieveWithDiscovery({retrieve: async () => [], discover: async () => {throw Error('upstream unavailable');}, allowDiscovery: true}), /upstream unavailable/);
 const {resolveExpandedRecommendationCandidates}=require('../ai/recommendationRetrieval');
 const requests=[];
 await resolveExpandedRecommendationCandidates({intent:{raw_prompt:'A newer thriller',hard_filters:{min_release_year:2005,max_release_year:2010,max_runtime_minutes:89,required_genre_ids:[53]},query_expansion:{title_hints:[],entity_aliases:[],entity_keyword_terms:[],search_terms:[],keyword_terms:[]}},fetchTmdb:async(path,params)=>{requests.push({path,params});return {results:[]};},fetchStructuredMoviesByIds:async()=>[],normalizeStructuredCandidate:x=>x});
 assert.equal(requests.length,3,'Keep the bounded catalog query budget');
 for(const {params} of requests) {
  assert.equal(params['primary_release_date.gte'],'2005-01-01');
  assert.equal(params['primary_release_date.lte'],'2010-12-31');
  assert.equal(params['with_runtime.lte'],89);
  assert.equal(params.with_genres,'53');
 }
 const fs=require('node:fs'),vm=require('node:vm');
 const source=fs.readFileSync(require.resolve('../index.js'),'utf8');
 const start=source.indexOf('const resolveGenreThemeCandidates =');
 const variantsEnd=source.indexOf('  const timeConstraintKeywordBaseParams',start);
 let range;
 const context=vm.createContext({uniqueStrings:x=>[...new Set(x)],resolveTmdbKeywordIds:async()=>[],mergeGenreIds:(...lists)=>[...new Set(lists.flat())],normalizePreferenceKey:()=> 'any',PICK_RUNTIME_CONFIG:{any:{}},buildTimeConstraintGenreFilter:()=> '35',buildTimeConstraintDiscoverVariants:options=>{range=options.runtimeRange;return [];}});
 vm.runInContext(source.slice(start,variantsEnd)+'return [];}; this.resolve=resolveGenreThemeCandidates;',context);
 await context.resolve({themes:[],genre_ids:[35]},{hard_filters:{max_runtime_minutes:89,min_runtime_minutes:40}});
 assert.equal(range.max,89,'Time-window retrieval uses the effective numeric cap rather than a UI runtime bucket');
 assert.equal(range.min,40);
 const excludedStart=source.indexOf('      const excludedTitles = Array.from(excludedIds)');
 const excludedEnd=source.indexOf('      const queries =',excludedStart);
 let cacheReads=0;
 const discoveryContext=vm.createContext({Set,excludedIds:new Set([101,102]),rankingPool:[{id:103,title:'Unselected alternative',plot_discovered:true}],tmdbCache:new Map(),stableStringify:JSON.stringify,readCache:(cache,key)=>{cacheReads++;return key.startsWith('/movie/101:')?{title:'Earlier primary'}:key.startsWith('/movie/102:')?{title:'Latest primary'}:null;}});
 vm.runInContext(source.slice(excludedStart,excludedEnd)+'this.testedTitles=testedTitles;',discoveryContext);
 assert.deepEqual(Array.from(discoveryContext.testedTitles),['Earlier primary','Latest primary','Unselected alternative'],'Discovery can avoid all previous primaries even after their IDs disappear from the swap deck');
 assert.equal(cacheReads,2,'Reuse cached identities without new metadata calls');
 console.log('Parallel independent retrieval, bounded call budget and transport propagation passed.');
})();
