const assert=require('node:assert/strict');const express=require('express');const axios=require('axios');
let server,app;const listen=express.application.listen;express.application.listen=function(){app=this;server=listen.call(this,0);return server;};
const calls=[];const movie={id:123,title:'Test Movie',release_date:'2000-01-01',overview:'A real overview.',runtime:95,genres:[{id:18,name:'Drama'}],credits:{cast:[{id:456,name:'Test Actor'}],crew:[{id:789,name:'Test Director',job:'Director'}]},release_dates:{results:[]}};
axios.get=async(url,options={})=>{calls.push({url,params:Object.fromEntries(new URL(url).searchParams)});if(url.includes('/search/movie'))return {data:{results:[movie]}};if(url.includes('/search/person'))return {data:{results:[]}};if(url.includes('/movie/123'))return {data:movie};throw new Error('Unexpected upstream request');};
require('../index');
app.get('/_test-stream',(req,res)=>{res.set('Content-Type','text/event-stream');res.write('data: progress\n\n');setTimeout(()=>res.end('data: done\n\n'),100);});
(async()=>{try{const base=`http://127.0.0.1:${server.address().port}`;
for(const path of ['/movies/123?view=metadata','/movies/resolve/test-movie-2000?view=metadata']){const response=await fetch(base+path);assert.equal(response.status,200);const body=await response.json();assert.equal(body.canonical_slug,'test-movie-2000');assert.equal(body.description,'A real overview.');assert.equal(body.top_cast_credits[0].canonical_path,'/person/456');assert.ok(!('watch_providers' in body));assert.ok(!('similar' in body));}
assert.equal(calls.filter(c=>c.url.includes('/movie/123')).length,1);assert.equal(calls.find(c=>c.url.includes('/movie/123')).params.append_to_response,'credits,release_dates');assert.ok(!calls.some(c=>c.url.includes('/search/person')||c.url.includes('streaming')));
const cached=await fetch(base+'/movies/123?view=metadata');assert.equal(cached.headers.get('x-reelbot-catalog-cache'),'HIT');const full=await fetch(base+'/movies/123');assert.equal(full.status,200);assert.ok('watch_providers' in await full.json());assert.ok(calls.some(c=>c.params?.append_to_response?.includes('reviews')));
assert.equal(full.headers.get('content-encoding'),'gzip');
const stream=await fetch(base+'/_test-stream',{headers:{'Accept-Encoding':'gzip'}});assert.equal(stream.headers.get('content-encoding'),null);const reader=stream.body.getReader();const first=await reader.read();assert.match(Buffer.from(first.value).toString(),/progress/);assert.doesNotMatch(Buffer.from(first.value).toString(),/done/);await reader.cancel();
console.log('Catalog integration passed: slim API, full detail, gzip, cache, immediate SSE.');}finally{server.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
